"""WebSocket API commands for the Span Panel integration."""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any

from homeassistant.components import websocket_api
from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr, entity_registry as er
import voluptuous as vol

from .const import DOMAIN
from .control_gate import ControlMode
from .entity_resolver import entity_id_in_entry
from .helpers import (
    build_panel_unique_id,
    circuit_has_a_breaker_switch,
    circuit_has_a_priority_select,
    construct_voltage_attribute,
)
from .id_builder import build_binary_sensor_unique_id
from .runtime import SpanPanelRuntimeData, loaded_runtime_data
from .solar_topology import SolarTopology, solar_topology
from .util import classify_sub_device_identifier, pv_device_ref
from .websocket_adopted import handle_adopted_curate, handle_adopted_list
from .websocket_panel import resolve_panel_device

if TYPE_CHECKING:
    from span_panel_api import SpanCircuitSnapshot, SpanPanelSnapshot

# Mapping from unique_id suffixes to semantic role names for circuit sensors.
# Mapping from unique_id suffixes (as generated by build_circuit_unique_id via
# get_user_friendly_suffix) to semantic role names used in the topology response.
# NOTE: build_circuit_unique_id maps API keys through CIRCUIT_SUFFIX_MAPPING,
# so unique_ids end with e.g. "_power" not "_instantPowerW".
# Panel-level sensor keys to resolve via entity registry.
# Maps topology role name -> sensor description key (used by
# build_panel_unique_id to construct the unique_id).
_PANEL_SENSOR_KEYS: dict[str, str] = {
    "current_power": "instantGridPowerW",
    "site_power": "sitePowerW",
    "grid_power": "gridPowerFlowW",
    "feedthrough_power": "feedthroughPowerW",
    "pv_power": "pvPowerW",
    "battery_power": "batteryPowerW",
    "battery_level": "storage_battery_percentage",
    "dsm_state": "dsm_grid_state",
    "main_breaker_rating": "main_breaker_rating",
    "upstream_l1_current": "upstream_l1_current",
    "upstream_l2_current": "upstream_l2_current",
    "downstream_l1_current": "downstream_l1_current",
    "downstream_l2_current": "downstream_l2_current",
    "l1_voltage": "l1_voltage",
    "l2_voltage": "l2_voltage",
}

_SENSOR_ROLE_SUFFIXES: dict[str, str] = {
    "_power": "power",
    "_energy_produced": "produced_energy",
    "_energy_consumed": "consumed_energy",
    "_energy_net": "net_energy",
    "_current": "current",
    "_breaker_rating": "breaker_rating",
}


def async_register_commands(hass: HomeAssistant) -> None:
    """Register WebSocket commands for the Span Panel integration.

    Every command this integration answers is named here, including the adopted
    ones defined in `websocket_adopted`. The dependency runs one way -- that
    module never imports this one -- so registration stays a single list rather
    than something each module does for itself.
    """
    websocket_api.async_register_command(hass, handle_panel_topology)
    websocket_api.async_register_command(hass, handle_adopted_list)
    websocket_api.async_register_command(hass, handle_adopted_curate)


@websocket_api.websocket_command(
    {
        vol.Required("type"): "span_panel/panel_topology",
        vol.Required("device_id"): str,
    }
)
@websocket_api.require_admin
@websocket_api.async_response
async def handle_panel_topology(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Return the full panel topology with entity mappings.

    Admin users must pass the HA device registry ID for the **main SPAN panel**
    device only (not a sub-device). Returns panel metadata, circuits with
    tabs/entity mappings, and sub-devices -- every kind
    `classify_sub_device_identifier` names, which is BESS, MID, EVSE and PV.
    A PV sub-device also carries a `solar` block, the inverter it describes and
    the circuit reading that is its power; see `solar_topology`.
    """
    resolved = resolve_panel_device(hass, connection, msg)
    if resolved is None:
        return
    device_entry, config_entry = resolved
    config_entry_id = config_entry.entry_id
    device_registry = dr.async_get(hass)

    runtime_data = loaded_runtime_data(config_entry)
    if config_entry.state is not ConfigEntryState.LOADED or runtime_data is None:
        connection.send_error(msg["id"], "not_loaded", "SPAN Panel integration is not loaded")
        return
    coordinator = runtime_data.coordinator
    snapshot = coordinator.data

    if snapshot is None:
        connection.send_error(msg["id"], "no_data", "SPAN Panel has not yet provided any data")
        return

    # Build entity lookup grouped by device_id for sub-device section.
    entity_registry = er.async_get(hass)
    all_entities = er.async_entries_for_config_entry(entity_registry, config_entry_id)

    entities_by_device: dict[str, list[er.RegistryEntry]] = {}
    for entity in all_entities:
        if entity.device_id:
            entities_by_device.setdefault(entity.device_id, []).append(entity)

    # Resolve panel-level sensor entity_ids via unique_id registry lookup.
    panel_entities = _build_panel_entity_map(
        snapshot.serial_number, entity_registry, config_entry_id
    )

    panel_status_entity = _resolve_panel_status_entity(
        snapshot.serial_number, entity_registry, config_entry_id
    )
    if panel_status_entity is not None:
        panel_entities["panel_status"] = panel_status_entity

    # Single pass over all entities to build circuit_id to role to entity_id
    # map. EVSE feed circuit sensors live on the EVSE sub-device, so we
    # search all entities for the config entry, not just panel-device ones.
    circuit_ids = {cid for cid in snapshot.circuits if not cid.startswith("unmapped_tab_")}
    entity_map = _build_circuit_entity_map(circuit_ids, all_entities)
    # The `power` role of every circuit, for the `solar` blocks below.
    circuit_power = {cid: roles["power"] for cid, roles in entity_map.items() if "power" in roles}

    # Build circuits section.
    circuits: dict[str, dict[str, Any]] = {}
    for circuit_id, circuit in snapshot.circuits.items():
        if circuit_id not in circuit_ids:
            continue

        tabs = sorted(circuit.tabs) if circuit.tabs else []
        circuits[circuit_id] = {
            "tabs": tabs,
            "name": circuit.name or None,
            # Same inference as the entity attribute, from the same helper: a
            # pole count answers this for one and two poles and not beyond, and
            # null says so rather than the previous 120, which this branch
            # returned for every circuit that was not exactly two-pole.
            "voltage": construct_voltage_attribute(circuit),
            "device_type": circuit.device_type,
            "relay_state": circuit.relay_state,
            "relay_state_target": circuit.relay_state_target,
            "is_user_controllable": circuit.is_user_controllable,
            "breaker_rating_a": circuit.breaker_rating_a,
            "always_on": circuit.always_on,
            "priority": circuit.priority,
            "priority_target": circuit.priority_target,
            # Whether `priority` above can be written, which is a different
            # commissioning flag from `is_user_controllable`: that one governs
            # the relay. A never-backup circuit has a working relay and a
            # priority the panel pins, so a consumer that infers priority
            # settability from relay controllability gets it wrong in both
            # directions. Carried even though no entity is created for such a
            # circuit, because a consumer rendering from this record has no
            # other way to tell a pinned priority from an absent one.
            "is_never_backup": circuit.is_never_backup,
            "entities": _offered_roles(
                entity_map.get(circuit_id, {}), circuit, runtime_data.control_policy.mode
            ),
        }

    # Build sub-devices section from devices linked via via_device_id.
    sub_devices: dict[str, dict[str, Any]] = {}

    # Matched against the panel device itself rather than the id the request
    # carried: they differ when that id was saved before 2026.8, and every
    # sub-device links to the device -- see `resolve_panel_device`.
    for dev in dr.async_entries_for_config_entry(device_registry, config_entry_id):
        if dev.id == device_entry.id:
            continue
        if dev.via_device_id != device_entry.id:
            continue

        sub_device_entities = entities_by_device.get(dev.id, [])
        sub_device_type = _classify_sub_device(dev)

        record: dict[str, Any] = {
            "name": dev.name,
            "type": sub_device_type,
            "manufacturer": dev.manufacturer,
            "model": dev.model,
            "serial_number": dev.serial_number,
            "sw_version": dev.sw_version,
            "entities": {
                ent.entity_id: {
                    "domain": ent.domain,
                    "original_name": ent.original_name,
                    "unique_id": ent.unique_id,
                }
                for ent in sub_device_entities
            },
        }
        solar = _solar_block(
            dev, runtime_data, snapshot, circuit_power, panel_entities.get("pv_power")
        )
        if solar is not None:
            record["solar"] = solar
        sub_devices[dev.id] = record

    connection.send_result(
        msg["id"],
        {
            "serial": snapshot.serial_number,
            "firmware": snapshot.firmware_version,
            "panel_size": snapshot.panel_size,
            "device_id": msg["device_id"],
            # The panel's current device and the entry that owns it. They differ
            # from what the request carried only when that was an id saved before
            # 2026.8, which the device list no longer holds -- so a consumer takes
            # the panel's identity from here rather than looking up the id it has.
            "panel_device_id": device_entry.id,
            "config_entry_id": config_entry_id,
            "device_name": device_entry.name,
            "panel_entities": panel_entities,
            "circuits": circuits,
            "sub_devices": sub_devices,
        },
    )


def _classify_sub_device(device_entry: dr.DeviceEntry) -> str:
    """Classify a sub-device by its identifiers, or 'unknown'.

    The grammar lives with the builders that write it, in `util`, rather than
    being restated here. Restating it is how the MID went out as 'unknown' for a
    release — it was added to the writing end and not to this one — and how a
    consumer ended up rendering a device with a name and no type.

    'unknown' is still returned rather than propagated as None, because it is the
    documented wire value for this field and a consumer distinguishes on it.
    """
    for _, identifier in device_entry.identifiers:
        if (kind := classify_sub_device_identifier(identifier)) is not None:
            return kind
    return "unknown"


def _solar_block(
    device: dr.DeviceEntry,
    runtime_data: SpanPanelRuntimeData,
    live: SpanPanelSnapshot,
    circuit_power: Mapping[str, str],
    site_power_entity_id: str | None,
) -> SolarTopology | None:
    """Return the `solar` block for a PV device; see `solar_topology`.

    Structure is the setup snapshot's, from which the devices and the binding
    were built; identity and `circuit_power` come from the live one. A circuit
    gone from the live snapshot before the reload it causes therefore gives
    `power_entity_id: None` for that moment, which the card shows as no
    individual reading. That is accepted.
    """
    setup = runtime_data.setup_snapshot
    for domain, identifier in device.identifiers:
        if domain != DOMAIN:
            continue
        ref = pv_device_ref(identifier, setup.serial_number)
        if ref is not None:
            return solar_topology(
                ref.inverter_key,
                runtime_data.pv_binding,
                setup,
                live,
                circuit_power,
                site_power_entity_id,
            )
    return None


def _offered_roles(
    roles: Mapping[str, str], circuit: SpanCircuitSnapshot, mode: ControlMode
) -> dict[str, str]:
    """Return a circuit's roles without a `switch` or `select` the integration does not provide.

    The roles are read from the entity registry, which also holds a control kept
    under Nobody and, until the reload removes it, one the panel has withdrawn.
    Offering either would hand the card a switch that cannot be operated. The
    circuit is the live snapshot's, which covers the moment between a
    settability change and the reload it causes. `is_user_controllable`,
    `priority` and `is_never_backup` stay the panel's truth in the record.
    """
    offers_controls = mode is not ControlMode.DISABLED
    withheld = {
        role
        for role, provided in (
            ("switch", offers_controls and circuit_has_a_breaker_switch(circuit)),
            ("select", offers_controls and circuit_has_a_priority_select(circuit)),
        )
        if not provided
    }
    return {role: entity_id for role, entity_id in roles.items() if role not in withheld}


def _build_circuit_entity_map(
    circuit_ids: set[str],
    entities: list[er.RegistryEntry],
) -> dict[str, dict[str, str]]:
    """Build a circuit_id to {role: entity_id} map in a single pass.

    Iterates over entities once, matching each to a circuit by checking
    whether its unique_id contains a known circuit UUID.
    """
    result: dict[str, dict[str, str]] = {}

    for entity in entities:
        uid = entity.unique_id

        # Skip entities without a unique_id, as we cannot reliably match them.
        if not uid:
            continue

        # Find which circuit this entity belongs to.
        matched_circuit_id: str | None = None
        for cid in circuit_ids:
            # Avoid plain substring matching to prevent collisions like "1" in "15".
            idx = uid.find(cid)
            if idx == -1:
                continue

            # Require delimiters (or string boundaries) around the circuit_id.
            before_ok = idx == 0 or uid[idx - 1] in "_-"
            after_index = idx + len(cid)
            after_ok = after_index == len(uid) or uid[after_index] in "_-"

            if before_ok and after_ok:
                matched_circuit_id = cid
                break

        if matched_circuit_id is None:
            continue

        mapped = result.setdefault(matched_circuit_id, {})

        if entity.domain == "switch":
            mapped["switch"] = entity.entity_id
        elif entity.domain == "select":
            mapped["select"] = entity.entity_id
        elif entity.domain == "sensor":
            role = _classify_sensor_role(uid)
            if role:
                mapped[role] = entity.entity_id

    return result


def _build_panel_entity_map(
    serial: str,
    entity_registry: er.EntityRegistry,
    config_entry_id: str,
) -> dict[str, str]:
    """Resolve panel-level sensor unique_ids to current entity_ids.

    Returns a dict of {role: entity_id} for sensors registered in this config
    entry. Entries that cannot be resolved are omitted, as is a unique id that
    another entry holds.
    """
    result: dict[str, str] = {}
    for role, description_key in _PANEL_SENSOR_KEYS.items():
        unique_id = build_panel_unique_id(serial, description_key)
        entity_id = entity_id_in_entry(entity_registry, config_entry_id, "sensor", unique_id)
        if entity_id is not None:
            result[role] = entity_id
    return result


def _resolve_panel_status_entity(
    serial: str,
    entity_registry: er.EntityRegistry,
    config_entry_id: str,
) -> str | None:
    """Resolve the panel_status binary sensor entity_id for the frontend.

    The frontend watches this entity to detect panel online/offline state.
    The binary sensor is always available (see binary_sensor.py) so the
    frontend can rely on its state regardless of coordinator offline status.
    Looked up in this config entry only, as `_build_panel_entity_map` is.
    """
    unique_id = build_binary_sensor_unique_id(serial, "panel_status")
    return entity_id_in_entry(entity_registry, config_entry_id, "binary_sensor", unique_id)


def _classify_sensor_role(unique_id: str) -> str | None:
    """Classify a sensor's role from its unique_id suffix."""
    for suffix, role in _SENSOR_ROLE_SUFFIXES.items():
        if unique_id.endswith(suffix):
            return role
    return None
